image: gitpod/workspace-python-3.12

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg
      pip install fastapi python-multipart numpy opencv-python pydub tensorflow tensorflow-hub transformers uvicorn librosa
      mkdir -p /workspace/data
  - command: python main.py

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter